In [18]:
from numpy import array
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [1]:
# univariate data preparation
from numpy import array

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [2]:
X.shape

(6, 3)

In [4]:
t1 = [1,2,3,4,5]
t2 = [6,7,8,9,10]
t3 = [11,12,13,14,15]

t21 = [21,22,23,24,25]
t22 = [26,27,28,29,210]
t23 = [211,222,213,214,215]


In [5]:
s1 = [t1,t2,t3]
s2 = [t21,t22,t23]

In [6]:
ds = [s1,s2]

In [7]:
ds

[[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]],
 [[21, 22, 23, 24, 25], [26, 27, 28, 29, 210], [211, 222, 213, 214, 215]]]

In [9]:
ds_array = array(ds)
ds_array

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15]],

       [[ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29, 210],
        [211, 222, 213, 214, 215]]])

In [10]:
ds_array.shape

(2, 3, 5)

In [20]:
y = array([1,0])

In [21]:
# define model   Stacked LSTM
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(3, 5)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [23]:
# fit model
model.fit(ds_array, y, epochs=200, verbose=0)


Instructions for updating:
Use tf.cast instead.


In [30]:
s_test = array ([[[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3]]])

In [31]:
s_test.shape

(1, 3, 5)

In [33]:
yhat = model.predict(s_test, verbose=0)
print(yhat)

[[0.2500271]]


In [11]:
p = [1,2,3,4,5,6,7,8]

In [15]:
p_array = array(p)
p_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
p1= p_array.reshape((1,2,4))
p1

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [20]:
p1.shape

(1, 2, 4)